import { describe, expect, it } from "vitest";

import { appProductReadiness } from "./app-acceptance-data";
import { appSchema } from "./app-schema";
import { STUDIO_LAYER_TYPE_IDS } from "./studio-layers";
import { studioAssembleDeliverableSource } from "./studio-source";
import type { StudioStackSceneParameters } from "./studio-stack-render";

function scene(
  layers: StudioStackSceneParameters["layers"],
): StudioStackSceneParameters {
  return {
    backgroundColor: [0, 0, 0],
    cursor: [-9, -9],
    includeBackground: true,
    layers,
  };
}

const stripes = {
  typeId: "stripes" as const,
  values: {
    angle: 30,
    colorA: [1, 0, 0] as const,
    colorB: [0, 0, 1] as const,
    count: 12,
    opacity: 1,
    phase: 0,
    visible: 1,
    widthRatio: 0.5,
  },
};

/**
 * The names a delivered shader must not carry, in one place.
 *
 * Shared rather than repeated because the list is the claim: a second copy is a
 * second thing to forget to extend, and the marker that leaked last time would
 * have been caught by whichever copy someone remembered.
 */
const IDENTITY_MARKERS = [
  "Croix10",
  // The product was called this before the two apps became one, and a
  // delivered shader must not carry either name.
  "Shader Studio",
  "Toolcraft",
  "Generated",
  "generated by",
  "@author",
  "watermark",
] as const;

const gradient = {
  typeId: "gradient" as const,
  values: {
    angle: 0,
    colorA: [0, 0, 0] as const,
    colorB: [1, 1, 1] as const,
    opacity: 1,
    rampType: 1,
    visible: 1,
  },
};

/** The same two layers, following the pointer and pushed by it. */
const pointerStripes = {
  ...stripes,
  values: { ...stripes.values, engineCursor: 1, pointerPush: 0.8 },
};

const pointerGradient = {
  ...gradient,
  values: { ...gradient.values, engineCursor: 1, pointerPush: 0.6 },
};

describe("deliverable shader source", () => {
  it("leaves resolution as the only input the destination supplies", () => {
    const source = studioAssembleDeliverableSource(scene([stripes]));

    // Everything else is baked, so a host wires one uniform rather than fifty.
    expect(source).toContain("uniform vec2 uResolution;");
    expect(source).not.toContain("uniform float uLayer0_count;");
    expect(source).not.toContain("uniform vec3 uBackgroundColor;");
    expect(source).not.toContain("uniform float uIncludeBackground;");
  });

  it("bakes the values the author actually edited to", () => {
    const source = studioAssembleDeliverableSource(scene([stripes]));

    expect(source).toContain("const float uLayer0_count = 12.0;");
    expect(source).toContain("const float uLayer0_angle = 30.0;");
    expect(source).toContain("const vec3 uLayer0_colorA = vec3(1.0, 0.0, 0.0);");
  });

  it("keeps the baked values named so the result stays editable", () => {
    // The difference between a delivered shader and a screenshot of one: the
    // recipient can change a value in place rather than hunting literals through
    // the body.
    const source = studioAssembleDeliverableSource(scene([stripes]));

    expect(source).toContain("uLayer0_count");
    expect(source.match(/const float uLayer0_widthRatio = [\d.]+;/u)).not.toBeNull();
  });

  it("writes every float with a decimal point", () => {
    // GLSL has no implicit int-to-float conversion in a const initialiser, so an
    // integer-valued parameter emitted as "12" fails to compile at the far end
    // while looking perfectly reasonable here.
    const source = studioAssembleDeliverableSource(scene([stripes, gradient]));

    for (const match of source.matchAll(/const float \w+ = ([^;]+);/gu)) {
      expect(match[1], `${match[0]} must carry a decimal point`).toMatch(/\./u);
    }
  });

  it("carries no reference to the studio that produced it", () => {
    // The whole point of the artifact: it has to compile somewhere else. A
    // reference to the chunk registry, or to any studio helper the file does not
    // itself declare, would make that false.
    const source = studioAssembleDeliverableSource(scene([stripes, gradient]));

    expect(source).not.toContain("STUDIO_");
    expect(source).not.toContain("import");
    expect(source).not.toContain("studio-layers");
  });

  it("carries no watermark, attribution, or injected identifier", () => {
    const source = studioAssembleDeliverableSource(scene([stripes, gradient]));

    for (const marker of IDENTITY_MARKERS) {
      expect(source, `delivered source must not mention "${marker}"`).not.toContain(
        marker,
      );
    }
  });

  it("carries none of them with a pointer effect either", () => {
    // Not the same file. A stack that follows the pointer pulls in GLSL the
    // stack above never reaches -- the falloff, the displacement, and the
    // comments that explain them -- and a chunk comment ships verbatim. This
    // project has already leaked the product name exactly that way once: a
    // comment naming the prior art named the product beside it, and every
    // marker test in the suite passed because no fixture had turned the effect
    // on.
    const source = studioAssembleDeliverableSource(scene([pointerStripes, pointerGradient]));

    for (const marker of IDENTITY_MARKERS) {
      expect(source, `a pointer effect must not deliver "${marker}"`).not.toContain(
        marker,
      );
    }
  });

  it("delivers the pointer as a uniform the recipient drives", () => {
    // The half that makes the effect worth delivering at all: baked to the
    // author's last cursor position it would be a frozen smear rather than
    // something the recipient's own pointer moves.
    const source = studioAssembleDeliverableSource(scene([pointerStripes]));

    expect(source).toContain("uniform vec2 uCursor;");
    expect(source).not.toMatch(/const vec2 uCursor\b/u);
  });

  it("declares a body for every registered layer type", () => {
    // Whichever types a stack uses must arrive with it; a stack referencing a
    // body the file does not declare compiles here and fails there.
    for (const typeId of STUDIO_LAYER_TYPE_IDS) {
      const source = studioAssembleDeliverableSource(
        scene([typeId === "stripes" ? stripes : gradient]),
      );
      const entryPoint =
        typeId === "stripes" ? "studioStripesBody" : "studioGradientBody";

      expect(source).toContain(`vec4 ${entryPoint}(`);
      expect(source).toContain(`${entryPoint}(fragmentPosition`);
    }
  });

  it("assembles a mixed stack in draw order with separate namespaces", () => {
    const source = studioAssembleDeliverableSource(scene([stripes, gradient]));

    expect(source).toContain("const float uLayer0_count = 12.0;");
    expect(source).toContain("const float uLayer1_rampType = 1.0;");
    expect(source.indexOf("studioStripesBody(fragmentPosition")).toBeLessThan(
      source.indexOf("studioGradientBody(fragmentPosition"),
    );
  });

  it("bakes the background and its inclusion", () => {
    const included = studioAssembleDeliverableSource(scene([stripes]));
    const excluded = studioAssembleDeliverableSource({
      backgroundColor: [0.25, 0.5, 0.75],
      cursor: [-9, -9],
      includeBackground: false,
      layers: [stripes],
    });

    expect(included).toContain("const float uIncludeBackground = 1.0;");
    expect(excluded).toContain("const float uIncludeBackground = 0.0;");
    expect(excluded).toContain(
      "const vec3 uBackgroundColor = vec3(0.25, 0.5, 0.75);",
    );
  });

  it("falls back to a type's own default for a value the record lacks", () => {
    const source = studioAssembleDeliverableSource(
      scene([{ typeId: "stripes", values: {} }]),
    );

    expect(source).toContain("const float uLayer0_count = 24.0;");
    expect(source).toContain("const vec3 uLayer0_colorA = vec3(1.0, 1.0, 1.0);");
  });
});

describe("clipboard delivery leaves artifact intent alone", () => {
  it("keeps exportIntent describing only image and video", () => {
    // Copying the source is an additional product action, not an export one. If
    // shipping it ever moved the recorded intent, the product would be claiming
    // a third artifact kind it does not encode, download, or prove.
    // Narrowed rather than asserted: readiness is a union, and a product that
    // slipped back to starter mode would make the rest of this vacuous.
    expect(appProductReadiness.mode).toBe("product");
    if (appProductReadiness.mode !== "product") return;

    expect(Object.keys(appProductReadiness.exportIntent).sort()).toEqual([
      "image",
      "video",
    ]);
    expect(appProductReadiness.exportIntent.video.mode).toBe("not-requested");
  });

  it("declares the copy action without an export role", () => {
    const actions = appSchema.panels.controls?.sections
      .flatMap((section) => Object.values(section.controls))
      .filter((control) => control.type === "panelActions")
      .flatMap((control) => control.actions ?? []);
    // An action may be declared as a bare string or as a typed object; only the
    // object form can carry a role, which is the thing under test here.
    const copy = actions?.find(
      (action) => typeof action === "object" && action.value === "copy-source",
    );

    expect(copy, "the copy-source action must be declared").toBeDefined();
    expect(
      typeof copy === "object" ? copy.role : undefined,
      "a role would make it an export action",
    ).toBeUndefined();
  });
});
